"use client";
import React, { useEffect, useRef, useState } from "react";
import PrimaryNavbar from "@/components/navbars/primary-navbar";
import SecondaryNavbar from "@/components/navbars/secondary-navbar";
import Footer from "@/components/landing-sections/footer";
import { RefObject } from "react";

export default function Disclaimer() {
  const scrollWrapperRef: RefObject<HTMLDivElement> = useRef(null);
  const [isSticky, setIsSticky] = useState(false);


  useEffect(() => {
    const scrollWrapper = scrollWrapperRef.current;

    const handleScroll = () => {
      if (scrollWrapper) {
        const offset = scrollWrapper.scrollTop;
        setIsSticky(offset > 0);
      }
    };

    if (scrollWrapper) {
      scrollWrapper.addEventListener("scroll", handleScroll);
    }

    return () => {
      if (scrollWrapper) {
        scrollWrapper.removeEventListener("scroll", handleScroll);
      }
    };
  }, []);

  return (
    <article
      ref={scrollWrapperRef}
      className="bg-backgroundClr scroll-wrapper"
    >
    <PrimaryNavbar />
    <SecondaryNavbar setISticky={isSticky} />
      
        <div className="flex flex-col justify-center py-12">

        <h1 className="gradient-text xl:text-[54px] text-[25px] md:text-[35px] font-semibold font-nunito text-center my-12">
Disclaimer        </h1>

        <div className="container text-textClr font-nunito flex flex-col gap-12">
            <div>
                <p className="text-lg font-normal"> The advice generated by this website is generated by artificial intelligence (AI). This is based on algorithms and data patterns, and should be considered as general information only. It is not tailored to individual circumstances and may not be suitable for your specific situation.
<br/><br/>While we strive to provide accurate and up-to-date information, AI-generated advice may not always reflect the complexities and nuances of real-world scenarios. Therefore, it should not be relied upon as a substitute for proper consideration of the relevant facts and circumstances.
<br/><br/>This site may contain hypertext links, frames or other references to other parties and their websites. 2ai PTY LTD cannot control the contents of those other sites, and makes no warranty about the accuracy, timeliness or subject matter of the material located on those sites. 2ai PTY LTD does not necessarily approve of, endorse, or sponsor any content or material on such sites. 2ai PTY LTD makes no warranties or representations that material on other websites to which this website is linked does not infringe the intellectual property rights of any person anywhere in the world.
<br/><br/>We provide no warranties or guarantees regarding the accuracy, reliability, or completeness of the AI-generated advice. Any reliance you place on such advice is strictly at your own risk. We disclaim all liability for any loss or damage that may arise from your use of or reliance on AI-generated advice provided herein.
                </p>
            </div>
            

        </div>
        </div>



    <Footer />
    </article>
  );
}

